### ISSUE TITLE
关于redis和mongodb的建议

### ISSUE THREAD

**Issue by eonun** [Autumn-27/ScopeSentry-Scan#1]
# 既然redis和mongodb是必须的，完全可以将docker-compose.yml合并为一个,没必要分开写

```yaml
version: "3.4"

services:
  mongodb:
    image: mongo:latest
    container_name: scopesentry-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_username
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - ./data/mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.11
    container_name: scopesentry-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_password
    volumes:
      - ./data/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
```

# redis和mongodb作为服务端的服务应当放到服务端的项目中去

作为服务端的服务应当将这个部署放到 Autumn-27/ScopeSentry 项目中，且完全可以将 Autumn-27/ScopeSentry 中的 docker-compose.yml 和 redis和mongodb 的 docker-compose.yml 合并，节点项目只对节点服务进行管理

通过 docker-compose 3.4 以后的版本可以通过条件依赖检查服务是否正常运行再运行

且同一个docker-compose 中的容器在同一个 Docker Compose 网络中，服务之间可以通过名称进行通信

```yaml
version: "3.4"

services:
  mongodb:
    image: mongo:latest
    container_name: scopesentry-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_username
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - ./data/mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.11
    container_name: scopesentry-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_password
    volumes:
      - ./data/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  scope-sentry:
    image: autumn27/scopesentry:latest
    container_name: scope-sentry
    depends_on:
      - mongodb
      - redis
    restart: always
    ports:
      - "8082:8082"
    environment:
      TIMEZONE: Asia/Shanghai
      MONGODB_IP: scopesentry-mongodb
      MONGODB_PORT: 27017
      DATABASE_NAME: ScopeSentry
      DATABASE_USER: mongodb_username
      DATABASE_PASSWORD: mongodb_password
      REDIS_IP: scopesentry-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
```
